/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifpr.paranavai.crudbasicoatividadeii.visao;


import br.ifpr.paranavai.crudbasicoatividadeii.persistencia.EstadoDAO;
import br.ifpr.paranavai.crudbasicoatividadeii.entidade.Estado;
import br.ifpr.paranavai.crudbasicoatividadeii.exceptions.PersistenceException;
import br.ifpr.paranavai.crudbasicoatividadeii.interfaces.IEstado;
import br.ifpr.paranavai.crudbasicoatividadeii.utils.Utils;
import br.ifpr.paranavai.crudbasicoatividadeii.validacao.Validacao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Willian
 */
public class CadastroEstado extends javax.swing.JFrame {
    
    private Estado estado;

    /**
     * Creates new form CadastroEstado
     */
    public CadastroEstado() {
        initComponents();
        habilitarDesabilitarCampos(null);
        SwingUtilities.invokeLater(newAtualizaEstadosAction());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoSigla = new javax.swing.JTextField();
        botaoIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelEstados = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estado");

        jLabel1.setText("Nome:");

        jLabel2.setText("Sigla:");

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        painelEstados.setEditable(false);
        jScrollPane1.setViewportView(painelEstados);

        jLabel3.setText("Id:");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoDeletar.setText("Deletar");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoDeletar)))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluir)
                    .addComponent(botaoAlterar)
                    .addComponent(botaoExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        habilitarDesabilitarCampos(TipoBotao.incluir);
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        if (Utils.isNumber(campoId.getText())) {
           try {
                IEstado iEstado = new EstadoDAO();
                Estado e = iEstado.findById(Integer.parseInt(campoId.getText()));
                if (e != null) {
                    campoSigla.setText(e.getSigla());
                    campoNome.setText(e.getNome());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), "Erro ao pesquisar Estado.", JOptionPane.ERROR_MESSAGE);
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Digite nÃºmero do Id vÃ¡lido.", 
                    "Campo Id", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
       habilitarDesabilitarCampos(TipoBotao.editar);
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        habilitarDesabilitarCampos(TipoBotao.excluir);
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        List<String> listaObrigatorio = Validacao.ValidaCamposEstado(campoNome.getText(), campoSigla.getText());
                
        if (listaObrigatorio.size() > 0) {
            String msg = "";
            msg = listaObrigatorio.stream().map((str) -> str + "\n").reduce(msg, String::concat);
            JOptionPane.showMessageDialog(this, msg, "Validação", JOptionPane.WARNING_MESSAGE);
        } else {
            if (campoId.isEnabled()) {
                if(!Utils.isNumber(campoId.getText())) {
                    JOptionPane.showMessageDialog(this, "Preencher o campo Id válido.", 
                            "Validação", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            Estado e = new Estado(campoId.getText().isBlank() ? null : Integer.parseInt(campoId.getText()) , campoSigla.getText().trim(), campoNome.getText().trim());   
            IEstado iEstado = new EstadoDAO();
            iEstado.save(e);
//            EstadoDAO estadoDAO = new EstadoDAO();
//            estadoDAO.save(e);
            
            SwingUtilities.invokeLater(newAtualizaEstadosAction());
            
            habilitarDesabilitarCampos(null);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        if(Utils.isNumber(campoId.getText())) {
            try {
                IEstado iEstado = new EstadoDAO();
                Estado e = iEstado.findById(Integer.parseInt(campoId.getText()));
                if (e != null) {
                    iEstado.remove(e);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), "Erro ao excluir Estado.", JOptionPane.ERROR_MESSAGE);
            }
            
            SwingUtilities.invokeLater(newAtualizaEstadosAction());
            habilitarDesabilitarCampos(null);
        } else {
            JOptionPane.showMessageDialog(this, "Preencher o campo Id válido.", 
                    "Validação", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEstado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSigla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane painelEstados;
    // End of variables declaration//GEN-END:variables

    private void atualizarListaEstados() {
//        try {
//            Connection conn = Banco.abrirConexao();
//            PreparedStatement ps = conn.prepareStatement("SELECT * FROM estado");
//            ResultSet rs = ps.executeQuery();            
//            String estados = "";
//            while (rs.next()) {
//                estados += rs.getInt("id") + " - ";
//                estados += rs.getString("sigla") + " - ";
//                estados += rs.getString("nome") + "\n";
//            }
//            painelEstados.setText(estados);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }
    
    public Runnable newAtualizaEstadosAction() {
        return new Runnable() {
            public void run() {
                try {
                    IEstado iEstado = new EstadoDAO();
                    List<Object[]> listEstados = iEstado.getAll();
                    String strEstado = "";
                    
                    List<Estado> result = new ArrayList<>(listEstados.size());
                    
                    for (Object[] row : listEstados) {
                        result.add(new Estado(null, (String) row[0], (String) row[1]));
                    }
                    
                    for (Estado estado : result) {
                        strEstado += estado.getSigla() + " - " + estado.getNome() + "\n";
                    }
                                        
                    painelEstados.setText(strEstado);
                } catch (PersistenceException ex) {
                    JOptionPane.showMessageDialog(CadastroEstado.this,
                        ex.getMessage(), "Erro ao consultar Estado(s)", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
    }
    
    enum TipoBotao {
        incluir,
        editar,
        excluir
    }
    
    private void habilitarDesabilitarCampos(TipoBotao tipo) {
        limpaCampos();
        
        if (null == tipo) {
            campoId.setEnabled(false);
            campoSigla.setEnabled(false);
            campoNome.setEnabled(false);
            botaoBuscar.setEnabled(false);
            botaoSalvar.setEnabled(false);
            botaoDeletar.setEnabled(false);
        } else switch (tipo) {
            case incluir:
                campoId.setEnabled(false);
                campoSigla.setEnabled(true);
                campoNome.setEnabled(true);
                botaoBuscar.setEnabled(false);
                botaoSalvar.setEnabled(true);
                botaoDeletar.setEnabled(false);
                break;
            case editar:
                campoId.setEnabled(true);
                campoSigla.setEnabled(true);
                campoNome.setEnabled(true);
                botaoBuscar.setEnabled(true);
                botaoSalvar.setEnabled(true);
                botaoDeletar.setEnabled(false);
                break;
            case excluir:
                campoId.setEnabled(true);
                campoSigla.setEnabled(false);
                campoNome.setEnabled(false);
                botaoBuscar.setEnabled(true);
                botaoSalvar.setEnabled(false);
                botaoDeletar.setEnabled(true);
                break;
            default:
                campoId.setEnabled(false);
                campoSigla.setEnabled(false);
                campoNome.setEnabled(false);
                botaoBuscar.setEnabled(false);
                botaoSalvar.setEnabled(false);
                botaoDeletar.setEnabled(false);
                break;
        }
    }
    
    private void limpaCampos() {
        campoId.setText("");
        campoSigla.setText("");
        campoNome.setText("");
    }
    
}
