package br.ifpr.paranavai.crudbasicoatividadeii.visao;

import br.ifpr.paranavai.crudbasicoatividadeii.entidade.Estado;
import br.ifpr.paranavai.crudbasicoatividadeii.entidade.Produto;
import br.ifpr.paranavai.crudbasicoatividadeii.exceptions.PersistenceException;
import br.ifpr.paranavai.crudbasicoatividadeii.interfaces.IProduto;
import br.ifpr.paranavai.crudbasicoatividadeii.persistencia.ProdutoDAO;
import br.ifpr.paranavai.crudbasicoatividadeii.utils.Utils;
import br.ifpr.paranavai.crudbasicoatividadeii.validacao.Validacao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sidney
 */
public class CadastroProduto extends javax.swing.JFrame {
    
    private Produto produto;
    
    /**
     * Creates new form CadastroPessoa
     */
    public CadastroProduto() {
        initComponents();
        SwingUtilities.invokeLater(newAtualizaProdutosAction());
        habilitarDesabilitarCampos(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelProdutos = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        botaoIncluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        campoQtdEntrada = new javax.swing.JTextField();
        campoQtdSaida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoCodBarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produto");

        jLabel1.setText("Nome:");

        painelProdutos.setEditable(false);
        jScrollPane1.setViewportView(painelProdutos);

        jLabel2.setText("Qtd. Entrada:");

        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Id:");

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel4.setText("Qtd. Saída:");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoDeletar.setText("Deletar");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cód. de Barras:");

        jLabel6.setText("Descrição:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoBuscar))
                                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoSalvar)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoQtdSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoDeletar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCodBarras)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoIncluir)
                    .addComponent(botaoAlterar)
                    .addComponent(botaoExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoQtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoQtdSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        habilitarDesabilitarCampos(TipoBotao.incluir);
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        if (Utils.isNumber(campoId.getText())) {
           try {
                IProduto iProduto = new ProdutoDAO();
                Produto p = iProduto.findById(Integer.parseInt(campoId.getText()));
                
                if (p != null) {
                    String strQtdSaida = p.getQtdSaida() == null ? "0" : p.getQtdSaida().toString();
                    System.out.println("Nome: " + p.getNome());
                    System.out.println("Descricao: " + p.getDescricao());
                    System.out.println("Qtd.Ent.: " + p.getQtdEntrada());
                    System.out.println("Qtd.Sai.: " + strQtdSaida);
                    System.out.println("Cod.Barras: " + p.getCodigoBarras());
                    
                    campoNome.setText(p.getNome());
                    campoDescricao.setText(p.getDescricao());
                    campoQtdEntrada.setText(p.getQtdEntrada().toString());
                    campoQtdSaida.setText(strQtdSaida);
                    campoCodBarras.setText(p.getCodigoBarras());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), "Erro ao pesquisar produto.", JOptionPane.ERROR_MESSAGE);
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Digite número do Id válido.", 
                    "Campo Id", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        habilitarDesabilitarCampos(TipoBotao.editar);
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        habilitarDesabilitarCampos(TipoBotao.excluir);
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        List<String> listaObrigatorio = Validacao.ValidaCamposProduto(
                campoNome.getText(), campoDescricao.getText(), 
                Integer.parseInt(campoQtdEntrada.getText()), 
                campoCodBarras.getText());
        
        if (listaObrigatorio.size() > 0) {
            String msg = "";
            msg = listaObrigatorio.stream().map((str) -> str + "\n").reduce(msg, String::concat);
            JOptionPane.showMessageDialog(this, msg, "Validação", JOptionPane.WARNING_MESSAGE);
        } else {
            if (campoId.isEnabled()) {
                if(!Utils.isNumber(campoId.getText())) {
                    JOptionPane.showMessageDialog(this, "Preencher o campo Id válido.", 
                            "Validação", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            Produto p = new Produto(campoId.getText().isBlank() ? null : Integer.parseInt(campoId.getText()), 
                    campoNome.getText(), campoDescricao.getText(),
                    Integer.parseInt(campoQtdEntrada.getText()), 
                    campoQtdSaida.getText().isBlank() ? null : Integer.parseInt(campoQtdSaida.getText()),
                    campoCodBarras.getText());
            
            System.out.println("==== Produto ===");
            System.out.println("Id: " + p.getId());
            System.out.println("Nome: " + p.getNome());
            System.out.println("Descrição: " + p.getDescricao());
            System.out.println("Qtd.Ent.: " + p.getQtdEntrada());
            System.out.println("Qtd.Sai.: " + p.getQtdSaida());
            
            IProduto iProduto = new ProdutoDAO();
            iProduto.save(p);
            
            SwingUtilities.invokeLater(newAtualizaProdutosAction());
            habilitarDesabilitarCampos(null);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        if(Utils.isNumber(campoId.getText())) {
            try {
                IProduto iProduto = new ProdutoDAO();
                Produto p = iProduto.findById(Integer.parseInt(campoId.getText()));
                
                if (p != null)
                    iProduto.remove(p);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), "Erro ao excluir Produto.", JOptionPane.ERROR_MESSAGE);
            }
            
            SwingUtilities.invokeLater(newAtualizaProdutosAction());
            habilitarDesabilitarCampos(null);
        } else {
            JOptionPane.showMessageDialog(this, "Preencher o campo Id válido.", 
                    "Validação", JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_botaoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoCodBarras;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoQtdEntrada;
    private javax.swing.JTextField campoQtdSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane painelProdutos;
    // End of variables declaration//GEN-END:variables
       
    
    
    private void habilitarDesabilitarCampos(TipoBotao tipo) {
        limpaCampos();
                
        if (null == tipo) {
            campoId.setEnabled(false);
            campoNome.setEnabled(false);
            campoDescricao.setEnabled(false);
            campoQtdEntrada.setEnabled(false);
            campoQtdSaida.setEnabled(false);
            campoCodBarras.setEnabled(false);
            botaoSalvar.setEnabled(false);
            botaoBuscar.setEnabled(false);
            botaoDeletar.setEnabled(false);
        } else switch (tipo) {
            case incluir:
                campoId.setEnabled(false);
                campoNome.setEnabled(true);
                campoDescricao.setEnabled(true);
                campoQtdEntrada.setEnabled(true);
                campoQtdSaida.setEnabled(true);
                campoCodBarras.setEnabled(true);
                botaoSalvar.setEnabled(true);
                botaoBuscar.setEnabled(false);
                botaoDeletar.setEnabled(false);
                break;
            case editar:
                campoId.setEnabled(true);
                campoNome.setEnabled(true);
                campoDescricao.setEnabled(true);
                campoQtdEntrada.setEnabled(true);
                campoQtdSaida.setEnabled(true);
                campoCodBarras.setEnabled(true);
                botaoSalvar.setEnabled(true);
                botaoBuscar.setEnabled(true);
                botaoDeletar.setEnabled(false);
                break;
            case excluir:
                campoId.setEnabled(true);
                campoNome.setEnabled(false);
                campoDescricao.setEnabled(false);
                campoQtdEntrada.setEnabled(false);
                campoQtdSaida.setEnabled(false);
                campoCodBarras.setEnabled(false);
                botaoSalvar.setEnabled(false);
                botaoBuscar.setEnabled(true);
                botaoDeletar.setEnabled(true);
                break;
            default:
                campoId.setEnabled(false);
                campoNome.setEnabled(false);
                campoDescricao.setEnabled(false);
                campoQtdEntrada.setEnabled(false);
                campoQtdSaida.setEnabled(false);
                campoCodBarras.setEnabled(false);
                botaoSalvar.setEnabled(false);
                botaoBuscar.setEnabled(false);
                botaoDeletar.setEnabled(false);
                break;
        }
    }
    
    enum TipoBotao {
        incluir,
        editar,
        excluir
    }
    
    private void limpaCampos() {
        campoId.setText("");
        campoNome.setText("");
        campoDescricao.setText("");
        campoQtdEntrada.setText("");
        campoQtdSaida.setText("");
        campoCodBarras.setText("");
    }
    
    public Runnable newAtualizaProdutosAction() {
        return new Runnable() {
            public void run() {
                try {
                    IProduto iProduto = new ProdutoDAO();
                    List<Object[]> rows = iProduto.getAll();
                    List<Produto> result = new ArrayList<>(rows.size());
                    String strProduto = "";
                                        
                    for (Object[] row : rows) {
                        result.add(new Produto((Integer) row[0], (String) row[1], (String) row[2], 
                                (Integer) row[3], (Integer) row[4], (String) row[5]));
                    }
                    
                    for (Produto produto : result) {                
                        strProduto += produto.getId() + " - ";
                        strProduto += produto.getNome() + " | ";
                        strProduto += "Qtd.Ent.:" + produto.getQtdEntrada() + " | ";
                        
                        String strQtdSaida = produto.getQtdSaida() == null ? "0" : produto.getQtdSaida().toString();
                        
                        strProduto += "Qtd.Sai.:" + strQtdSaida + "\n";
                    }
                    
                    painelProdutos.setText(strProduto);
                } catch (PersistenceException ex) {
                    JOptionPane.showMessageDialog(CadastroProduto.this,
                        ex.getMessage(), "Erro ao consultar Produto(s)", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
    }
}
